on: [push]

env:
  cache-version: v1
  repo-name: tidytranscriptomics-workshops/iscb2022_tidytranscriptomics
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  r-build-and-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_15
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v2

      - name: Query dependencies and update old packages
        run: |
          # We'll install the specific versions from the install instructions
          BiocManager::install("stemangiola/tidyseurat@v0.5.4")
          BiocManager::install("stemangiola/tidySingleCellExperiment@v1.9.1")
          BiocManager::install("stemangiola/tidybulk@v1.11.1")
          BiocManager::install("stemangiola/tidySummarizedExperiment@v1.9.2")
          
          # Then install the other dependencies in the usual way
          BiocManager::install(ask=FALSE)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-
          
       # This lets us augment with additional dependencies	
      - name: Install system dependencies	
        if: runner.os == 'Linux'	
        env:	
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc	
        run: |	
          Rscript -e "remotes::install_github('r-hub/sysreqs')"	
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")	
          sudo -s eval "$sysreqs"
          
      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          BiocManager::repositories()
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Build pkgdown
        if: github.ref == 'refs/heads/main' 
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site(".")'

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        if: github.ref == 'refs/heads/main'
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy

        
